name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: run EpsilonHermesSetup
      run: ./EpsilonHermesSetup.sh
    
    - run: conan user -p solarcarAction1 -r epsilon action
    - run: conan config set general.revisions_enabled=1
    - name: Creating build folder
      run: mkdir build && cd build
    - name: install package with conan
      run: conan install ../Epsilon-Hermes --build=missing -s compiler.libcxx="libstdc++11"
    - name: qmake
      run: qmake ../Epsilon-Hermes/src/
    - run: make
    - run: make check
